### PR TITLE
spelling	modified:   web/_posts/2018-08-10-hello-cattlepi.md

### PR DESCRIPTION
**Pull request by stevendlewis**
spelling	modified:   web/_posts/2018-08-21-pihole-and-usercode.md
spelling	modified:   web/_posts/2018-08-28-hacking-bootcode.md
spelling	modified:   web/_posts/2018-10-11-pihole-image.md
spelling	modified:   web/_posts/2018-10-11-raspbian-stock-image.md
spelling	modified:   web/howto.md
spelling	modified:   web/images.md

### CODE REVIEW

**Comment by stevendlewis** [comment]
Fixed only spelling errors for now.

**Comment by stevendlewis** [comment]
Oops. Didn't mean to close.

**Comment by t3spe** [comment]
this is great.
from looking at it i'm impressed how many errors are actually in there :(
let me know when ready and I will take a final last look + merge and publish.

thank you!

**Comment by stevendlewis** [comment]
happy to help.
ready...please merge and publish.

**Review by t3spe — APPROVED** [review]

**Pull request merged**
